feat: Introduce message templates (#10)
## Motivation

Sometimes there's a need for a more advanced mechanism of error message
overriding and manipulation other than overriding the whole message with
`WithMessage`.
The most prominent example of such use case are translations.
Currently govy does not support translations in anyway.

Solution which would open up support for the aforementioned use cases is
introducing templating to all the builtin rules.
Similar solution was implemented by Fluent Validation
[here](https://docs.fluentvalidation.net/en/latest/configuring.html).

Go already has a native [templating
system](https://pkg.go.dev/text/template) which we can utilize to
achieve a similar API to the Fluent's version.
I'm opting for a verbose placeholders methods instead of extending
`WithMessage` functionality, one which would accept `template.Template`
(gives more power over the template initialization, parsing etc.)
another which would accept a raw template string.

## Summary

```go
package examples

import (
	"fmt"

	"github.com/nobl9/govy/pkg/govy"
	"github.com/nobl9/govy/pkg/rules"
)

func Example_messageTemplates() {
	type Teacher struct {
		Name string `json:"name"`
	}

	templateString := "name length should be between {{ .MinLength }} and {{ .MaxLength }} {{ formatExamples .Examples }}"

	v := govy.New(
		govy.For(func(t Teacher) string { return t.Name }).
			WithName("name").
			Rules(
				rules.StringLength(5, 10).
					WithExamples("Joanna", "Jerry").
					WithMessageTemplateString(templateString),
			),
	).WithName("Teacher")

	teacher := Teacher{Name: "Tom"}
	err := v.Validate(teacher)
	if err != nil {
		fmt.Println(err)
	}

	// Output:
	// Validation for Teacher has failed for the following properties:
	//   - 'name' with value 'Tom':
	//     - name length should be between 5 and 10 (e.g. 'Joanna', 'Jerry')
```

### Creating templates

Message templates can be either provided in form of a
`template.Template` or a raw template string.

### Template variables

Variables used to execute templates are defined exclusively by
`govy.TemplateVars` struct.
Builtin variables are defined at the top level, user defined variables
must be provided via `Custom` field of `govy.TemplateVars`.

### Adding template support to custom rules

Users can add templating support to their custom rules by returning a
`govy.RuleErrorTemplate` error.
This `error` is not meant to be called directly but rather it serves as
a container destined to be unpacked inside `govy.Rule.Validate`
function.

Currently, if a template was added to a rule which does not return
`govy.RuleErrorTemplate` it will panic in runtime. This behaviour is
expected to be improved upon.

### Builtin template functions

Common, builtin template functions (like `formatExamples`) can be added
to the user's templates with `govy.AddTemplateFunctions` function.
The following functions are added (more are expected to be defined as
all builtin rules adopt templating):
- `formatExamples`
- `joinStringSlice`

To improve the documentation for these builtin functions I decided to
document them at their definitions, combine these code comments and add
them to `govy.AddTemplateFunctions` code docs.

The automation for this process is done with `go generate` and a custom
program called `docextractor`.

## Release Notes

Added `govy.Rule.WithMessageTemplate` and
`govy.Rule.WithMessageTemplateString` functions which allow advanced
manipulation of the error message produced by `govy.Rule`.

Users can add templating support to their rules by returning a new
error: `govy.RuleErrorTemplate`.
This error is a simple container that passes `govy.TemplateVars` to the
rule evaluation logic which uses it as variables to execute an error
message template.
User defined variables should be provided via `govy.TemplateVars.Custom`
field which accepts `any` value.

Added `govy.AddTemplateFunctions` which adds builtin template functions
to the user's `template.Template` instance.